### PR TITLE
Add server-side rendering functionality

### PR DESCRIPTION
**Pull request by ghost**
Hi!

I took a stab at fixing #8, by adding another module to the package useful for rendering React components to HTML strings (for server-side apps)

It supports the ability to render JSX from strings or from files using the existing JSX transformer, as well as loading React components from strings or files for use when rendering.

Cheers!

### CODE REVIEW

**Comment by kmeht** [comment]
Thanks @bspoon! Have you signed our CLA yet? https://code.facebook.com/cla

**Comment by bspoon** [comment]
Yep!

**Comment by pyeekwr** [comment]
I would really like to see this merged. I ended up rolling my own in the meantime but that isn't really ideal.

**Comment by sontek** [comment]
@kmeht @marioidival Any feedback on this?

**Pull request closed without merging**
