### PR TITLE
Add Django Compressor compiler.

### PR DESCRIPTION
**Pull request by frgtn**
This adds a very simple [Django Compressor](https://github.com/django-compressor/django-compressor/) compiler for JSX.

I haven't included any tests since it would require pulling in `django-compressor` as a test dependency.

Is there a way to sign the CLA without creating a facebook account?

### CODE REVIEW

**Comment by zpao** [comment]
I don't think the CLA requires a FB account (anymore, there was a time it did and we would send a PDF to you). The one linked in the contributing doc might be out of date but https://code.facebook.com/cla looks like it should be fine without an account.

**Comment by frgtn** [comment]
I tried https://developers.facebook.com/opensource/cla and it required me to sign in. The code.facebook.com link worked without an account, thanks.

**Comment by davidfischer-ch** [comment]
+1

**Comment by chompomonim** [comment]
Why this PR is still mot merged?

**Comment by sophiebits** [comment]
As the README says, this project isn't maintained any more (hence why it's in facebookarchive). Sorry.

**Pull request closed without merging**
